import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import bcrypt from "bcryptjs";
import { prisma } from "@/lib/prisma";
import { checkRateLimit, getClientIp } from "@/lib/rate-limit";
import { hashResetToken } from "@/lib/password-reset";

const RESET_LIMIT = 10;
const RESET_WINDOW_MS = 15 * 60 * 1000;

const resetPasswordSchema = z.object({
  token: z.string().min(1),
  password: z.string().min(8),
});

/**
 * @swagger
 * /api/reset-password:
 *   post:
 *     summary: Set a new password using a reset link
 *     description: >
 *       Consumes a one-time reset link generated by an admin (see
 *       POST /api/admin/users/{id}/reset-link). On success, also revokes every existing
 *       API key for the account (credential rotation) — lock status is left unchanged.
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [token, password]
 *             properties:
 *               token:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Password updated
 *       400:
 *         description: Invalid body, or the link is invalid, expired, or already used
 *       429:
 *         description: Too many attempts — try again later
 */
export async function POST(req: NextRequest) {
  const rateLimit = await checkRateLimit("reset-password", getClientIp(req), RESET_LIMIT, RESET_WINDOW_MS);
  if (!rateLimit.allowed) {
    return NextResponse.json(
      { message: "Too many attempts. Please try again later." },
      { status: 429, headers: { "Retry-After": String(rateLimit.retryAfterSeconds) } }
    );
  }

  const body = await req.json().catch(() => null);
  const parsed = resetPasswordSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ message: "Invalid request body.", issues: parsed.error.issues }, { status: 400 });
  }

  const { token, password } = parsed.data;

  const invalidLinkResponse = () =>
    NextResponse.json({ message: "This reset link is invalid, expired, or has already been used." }, { status: 400 });

  const resetToken = await prisma.passwordResetToken.findUnique({ where: { tokenHash: hashResetToken(token) } });

  if (!resetToken || resetToken.consumedAt || resetToken.expiresAt < new Date()) {
    return invalidLinkResponse();
  }

  const passwordHash = await bcrypt.hash(password, 10);

  await prisma.$transaction([
    prisma.user.update({ where: { id: resetToken.userId }, data: { passwordHash } }),
    prisma.passwordResetToken.update({ where: { id: resetToken.id }, data: { consumedAt: new Date() } }),
    prisma.apiKey.deleteMany({ where: { userId: resetToken.userId } }),
  ]);

  return NextResponse.json({ message: "Password updated. You can now log in." });
}
